### ISSUE TITLE
ExceptionInInitializerError during Device startup due to NullPointerException on at org.slf4j.impl.SimpleLogger.write

### ISSUE THREAD

**Issue by xuai99** [qos-ch/slf4j#440] opened 2024-10-29 06:41 UTC
"crashReason": "java.lang.ExceptionInInitializerError", "Back Trace": [ "at com.NetworkApplication.JMDNS.service.core.managers.jettyManager.JettyManager$StartJettyThread.run(JettyManager.java:702)", "at java.lang.Thread.run(Thread.java:1012)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.println(java.lang.String)' on a null object reference", "at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:381)", "at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:376)", "at org.slf4j.impl.SimpleLogger.formatAndLog(SimpleLogger.java:430)", "at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:562)", "at org.eclipse.jetty.util.log.Slf4jLog.info(Slf4jLog.java:77)", "at org.eclipse.jetty.util.log.Log.initialized(Log.java:170)", "at org.eclipse.jetty.util.log.Log.getLogger(Log.java:278)", "at org.eclipse.jetty.util.log.Log.getLogger(Log.java:267)", "at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:36)", "... 2 more" ] }

My android project is pointing to "implementation ('org.slf4j:slf4j-simple:1.7.9')" do i have to upgrade to a latest version to prevent this issue? if yes what version should i upgrade to?

**Comment by ceki** [comment] 2024-10-29 08:33
@xuai99 Looking at [SimpleLogger in version 1.7.9](https://github.com/qos-ch/slf4j/blob/v_1.7.9/slf4j-simple/src/main/java/org/slf4j/impl/SimpleLogger.java), the issue stems from an initialization problem. Since Jetty log is the caller, I suggest you inquire with the Jetty team. 

In the mean time, I am closing this ticket as NOT_A_BUG, CANT_REPRODUCE.

**Closed** 2024-10-29 08:34 UTC
Labels: NOT_A_BUG, INCOMPLETE

**Comment by xuai99** [comment] 2024-10-30 06:52
okay thanks, I'll route this to jetty team
